# Generated by Django 5.0 on 2023-12-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0009_alter_medical_drug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_drug',
            name='status',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'На рассмотрении'), (2, 'Завершён'), (3, 'Отменён'), (4, 'Удалён')], default=0),
        ),
    ]
