# Generated by Django 5.0 on 2023-12-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0010_alter_medical_drug_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': True},
        ),
    ]
