# Generated by Django 5.0 on 2023-12-26 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0011_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_drug',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
