# Generated by Django 5.0 on 2023-12-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0012_medical_drug_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_drug',
            name='status',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Сформирована'), (2, 'Завершён'), (3, 'Отменён'), (4, 'Удалён')], default=0),
        ),
        migrations.AlterField(
            model_name='medical_drug',
            name='time_create',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_drug',
            name='time_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_drug',
            name='time_form',
            field=models.DateField(blank=True, null=True),
        ),
    ]
